name: Python package

on: [push, pull_request]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: pipenv install --python 3.5
      - name: generate code
        run: (make api | tee generate-stdout.log) 3>&1 1>&2 2>&3  3>&- | tee generate-stderr.log
      - name: verify no stderr
        run: "[ ! -s generate-stderr.log ]"
      - uses: actions/upload-artifact@master
        with:
          name: generated-api
          path: api

  test:
    needs: generate
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: pipenv install --python ${{ matrix.python-version }}

    - uses: actions/download-artifact@master
      with:
        name: generated-api
        path: api

    - name: install for test
      run: |
        pipenv install --dev
        pipenv run pip freeze
    - name: Test with pytest
      run: pipenv run pytest --cov=api
    - name: Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.coveralls_repo_token }}
      run: pipenv run coveralls

  publish:
    needs:
      - test
      - generate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: pipenv --python 3.5 install

    - uses: actions/download-artifact@master
      with:
        name: generated-api
        path: api

    - name: Build package
      run: |
        cd api
        pipenv run python setup.py sdist bdist_wheel
    - name: Twine check
      run: pipenv run twine check api/dist/*
    - name: test upload
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.testpypi_password }}
      run: |
        pipenv run twine upload --repository-url https://test.pypi.org/legacy/ api/dist/*
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        pipenv run twine upload api/dist/*

  cleanup_job:
    needs: publish
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: call webhook to delete artifacts
      env:
        FOR_WEBHOOKS_SECRET: ${{ secrets.FOR_WEBHOOKS_SECRET }}
      run: |
        echo "::add-mask::$FOR_WEBHOOKS_SECRET"
        curl --verbose --fail --show-error --location --request POST "https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches" --header "Authorization: token $FOR_WEBHOOKS_SECRET" --header 'Content-Type: application/json' --header 'Accept: application/vnd.github.everest-preview+json' --data-raw "{ \"event_type\": \"delete_all_artifacts\", \"client_payload\": {\"parent_runid\": \"$GITHUB_RUN_ID\", \"parent_repo\": \"$GITHUB_REPOSITORY\"} }"
